type Product {
    id: ID!
    name: String!
    priceCents: Int!
    reviews: [Review!]!
}

type Review {
    id: ID!
    productId: ID!
    author: String!
    rating: Int!
    comment: String
}

type Query {
    products: [Product!]!
    product(id: ID!): Product
}

type Mutation {
    addReview(input: AddReviewInput!): Review!
}

type Subscription {
    reviewAdded(productId: ID): Review!
}

input AddReviewInput {
    productId: ID!
    author: String!
    rating: Int!
    comment: String
}
