name: azure-service-bus

services:
  sqledge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqledge
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "ServiceBus123!"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "ServiceBus123!", "-Q", "SELECT 1", "-b"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s

  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    container_name: servicebus-emulator
    environment:
      ACCEPT_EULA: "Y"
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "ServiceBus123!"
    ports:
      - "5672:5672"
    volumes:
      - ./config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
    depends_on:
      sqledge:
        condition: service_healthy
