server:
  port: 8087

openai:
  api-key: ${OPENAI_API_KEY:}
  base-url: https://api.openai.com
  model: text-embedding-3-small

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
